language: c

dist: focal # xenial

arch:
  - amd64

os:
  - linux

compiler:
  - gcc
  - clang

env:
  global: CFLAGS="-W -Wall -Werror -Wextra"
  jobs:
    - T_CFLAGS=
    - T_CFLAGS="-DNDEBUG"
    - T_CFLAGS="-DUSE_SIGNALFD"
    - T_CFLAGS="-DUSE_SIGNALFD -DNDEBUG"

jobs:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: T_CFLAGS="-DUSE_SIGNALFD"
    - os: osx
      env: T_CFLAGS="-DUSE_SIGNALFD -DNDEBUG"

script:
  - make --version
  - make src/config.h
  - make
  - make example
  - make check

after_failure:
  less src/config.h
  less $(find . -type f -name *.ko)

notifications:
  email: false
